spring:
  application:
    name: wetools-cmdb
  profiles:
    active: dev
logging:
  level:
    root: debug
  config: classpath:logback-spring.xml
  file:
    path: logs/springboot.log
server:
  port: 8080

